services:
  # Backend - Flask
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matcha_backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mariadb
    networks:
      - m-network-back

  # Frontend - React
  frontend:
    image: node:20-alpine
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: matcha_frontend
    env_file: .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
    ports:
      - "3000:3000"
    networks:
      - m-network-front

  # Base de Données - MySQL
  mariadb:
    image: mariadb:latest
    env_file: .env
    volumes: 
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - m-network-back


  # Serveur Web - Nginx
  nginx:
    image: nginx:latest
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    container_name: matcha_nginx
    env_file: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Fichier de config Nginx
      - ./frontend/build:/var/www/html/frontend # Frontend en mode production
      - ./backend/public:/var/www/html/backend # Point d'entrée pour Flask
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - m-network-front
      - m-network-back

networks:
  m-network-back:
  m-network-front:

volumes:
  db_data:
